// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2weA8Umd3XidnrFdkt-O4gBJWB7pJ8A',
    appId: '1:992234390083:web:2fadef2211be3e45750af6',
    messagingSenderId: '992234390083',
    projectId: 'fir-db-90228',
    authDomain: 'fir-db-90228.firebaseapp.com',
    storageBucket: 'fir-db-90228.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYo3qY5pHq9_edhYcUQS0CvW1aWJCil-0',
    appId: '1:992234390083:android:39f5739664887c00750af6',
    messagingSenderId: '992234390083',
    projectId: 'fir-db-90228',
    storageBucket: 'fir-db-90228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJM6fJk8BLj_tMZN3ITQDX1go1DUsuprc',
    appId: '1:992234390083:ios:377f272f31b76875750af6',
    messagingSenderId: '992234390083',
    projectId: 'fir-db-90228',
    storageBucket: 'fir-db-90228.appspot.com',
    iosBundleId: 'com.example.artApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJM6fJk8BLj_tMZN3ITQDX1go1DUsuprc',
    appId: '1:992234390083:ios:b051dda0be3f84e1750af6',
    messagingSenderId: '992234390083',
    projectId: 'fir-db-90228',
    storageBucket: 'fir-db-90228.appspot.com',
    iosBundleId: 'com.example.artApp.RunnerTests',
  );
}
